### ISSUE TITLE
DWC post edit requests

### ISSUE THREAD

**Issue by tchoi8** [SFPC/codesocieties-winter-19#14]
re posting on [DWC](https://github.com/SFPC/codesocieties-winter-19/blob/master/_posts/2019-1-11-distributed-webo-of-care-blog.md) class

- URL contains typo -- webo-of-care 
- "have abstracted infrastructural problems into logistical problems." - quote ingrid on [the Atlantic](https://www.theatlantic.com/technology/archive/2016/01/amazon-web-services-data-center/423147/)
- Jo Freeman, who advocated for the distribution of authority among as many people as reasonably possible as a way to counter authoritarian structures. - quote [jo](https://www.jofreeman.com/joreen/tyranny.htm)
- "A screenshot from Domesticated Mountain by Andreas Angelidakis." Screenshot from Domesticated Mountain  - image link broken

**Comment by brightredchilli** [comment]
addressed! Thanks for checking these!

**Comment by brightredchilli** [comment]
Updated at: http://sfpc.io/codesocieties-winter-19/2019/01/11/distributed-web-of-care-blog.html
